### PR TITLE
Bumped release

### PR DESCRIPTION
**Pull request by spike77453**
dnf seems to get confused by the fact, that there are a couple of builds with the same version '0.19.1-1.fc28' available at 'oranenj/znapzend'. It seems to pull the oldest version that built ok which results in:

```
"slurp" is not exported by the Mojo::Util module
Can't continue after import errors at /usr/share/perl5/vendor_perl/ZnapZend.pm line 5.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/ZnapZend.pm line 5.
Compilation failed in require at /usr/bin/znapzend line 9.
BEGIN failed--compilation aborted at /usr/bin/znapzend line 9
```

(and some missing required packages). This should be fixed by a simple version bump since there's already a proper patch that addresses the slurp issue (`00_remove_deprecated_slurp.patch`) and proper `build requires`.

### CODE REVIEW

**Comment by spike77453** [comment]
Removing other builds with version '0.19.1-1.fc28' so there's only one left in copr should work fine as well
